run_kafka_read_data:
	spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1,org.elasticsearch:elasticsearch-spark-30_2.12:8.2.0 /mnt/disk1/hachi/BigData_nhom10/stream/spark_read_data.py > /mnt/disk1/hachi/BigData_nhom10/logs/spark_read_data.log 2>&1
